version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mealplanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - ./backend/db/seed_users.sql:/docker-entrypoint-initdb.d/01-seed_users.sql:ro
      - ./backend/db/seed_ingredients.sql:/docker-entrypoint-initdb.d/02-seed_ingredients.sql:ro
      - ./backend/db/seed_meals.sql:/docker-entrypoint-initdb.d/03-seed_meals.sql:ro
      - ./backend/db/seed_fridge_ingredients.sql:/docker-entrypoint-initdb.d/04-seed_fridge_ingredients.sql:ro
      - ./backend/db/seed_meal_ingredients.sql:/docker-entrypoint-initdb.d/05-seed_meal_ingredients.sql:ro

volumes:
  pgdata: