-- Przykładowe składniki (30)
INSERT INTO ingredients (name) VALUES
('Pomidor'),
('Ogórek'),
('Ser feta'),
('Kurczak'),
('Ryż'),
('Płatki owsiane'),
('Miód'),
('Owoce'),
('Sałata'),
('Cebula'),
('Czosnek'),
('Papryka'),
('Marchewka'),
('Ziemniaki'),
('Makaron'),
('Tuńczyk'),
('Jajka'),
('Szpinak'),
('Kukurydza'),
('Jogurt'),
('Awokado'),
('Banan'),
('Truskawki'),
('Migdały'),
('Orzechy włoskie'),
('Ser żółty'),
('Masło'),
('Mleko'),
('Kiełbasa'),
('Chleb');