INSERT INTO meals (name, description, calories) VALUES
('Sałatka grecka', 'Sałatka z pomidorów, ogórków, oliwek i sera feta.', 250),
('Kurczak z ryżem', 'Pieczony kurczak z ryżem i warzywami.', 550),
('Owsianka', 'Owsianka z owocami i miodem.', 300),
('Spaghetti Bolognese', 'Makaron z sosem mięsnym i pomidorowym.', 600),
('Tosty z awokado', 'Chleb tostowy z awokado i jajkiem.', 350),
('Omlet ze szpinakiem', 'Jajka z szpinakiem i serem żółtym.', 400),
('Sałatka z tuńczykiem', 'Tuńczyk z sałatą, kukurydzą i jajkiem.', 320),
('Zupa pomidorowa', 'Klasyczna zupa pomidorowa z makaronem.', 280),
('Kanapka z kiełbasą', 'Chleb z kiełbasą, serem i warzywami.', 450),
('Smoothie bananowe', 'Banan, jogurt i miód zmiksowane na smoothie.', 220),
('Risotto z kurczakiem', 'Kremowe risotto z kurczakiem i warzywami.', 580),
('Sałatka owocowa', 'Mix świeżych owoców z miodem.', 210),
('Zapiekanka ziemniaczana', 'Ziemniaki zapiekane z serem i boczkiem.', 650),
('Pasta z awokado', 'Makaron z kremową pastą z awokado.', 420),
('Jajka sadzone z kiełbasą', 'Jajka sadzone podane z kiełbasą.', 500),
('Kanapka z serem żółtym', 'Chleb z masłem i serem żółtym.', 300),
('Sałatka warzywna', 'Mix sałaty, papryki, cebuli i marchewki.', 280),
('Płatki owsiane z mlekiem', 'Płatki owsiane zalane mlekiem.', 330),
('Koktajl truskawkowy', 'Truskawki zmiksowane z jogurtem i mlekiem.', 240),
('Grillowana pierś kurczaka', 'Pierś kurczaka z przyprawami i warzywami.', 520),
('Tortilla z warzywami', 'Tortilla z warzywami i serem feta.', 460),
('Zupa jarzynowa', 'Zupa z marchewki, ziemniaków i kukurydzy.', 300),
('Placki ziemniaczane', 'Smażone placki z ziemniaków.', 550),
('Sałatka z awokado i orzechami', 'Awokado z orzechami włoskimi i sałatą.', 400),
('Kanapka z masłem orzechowym i bananem', 'Chleb z masłem orzechowym i plasterkami banana.', 350),
('Smażony ryż z warzywami', 'Ryż smażony z marchewką i papryką.', 480),
('Jajecznica z cebulą', 'Jajecznica z cebulą i masłem.', 420),
('Makaron z sosem śmietanowym', 'Makaron z kremowym sosem i szpinakiem.', 530),
('Szaszłyki z kurczaka', 'Grillowane szaszłyki z kurczaka i papryki.', 490),
('Jogurt z migdałami', 'Jogurt naturalny z migdałami i miodem.', 250),
('Chleb z masłem i dżemem', 'Prosta kanapka z masłem i dżemem.', 320);
